### ISSUE TITLE
In full-screen mode mouse clicks at spot slightly above mouse indicator.

### ISSUE THREAD

**Issue by opfermann** [AGPlested/ASCAM#5] opened 2019-01-21 10:15 UTC
![screenshot 2019-01-21 at 10 45 45](https://user-images.githubusercontent.com/26271459/51467833-c7aaa180-1d6d-11e9-9b2d-ad9a2afd9de7.png)

**Comment by opfermann** [comment] 2019-01-21 10:16
The mouse is not shown here, but when clicking on episode #0 the mouse clicks GFILTER1000.BC.

**Comment by imLew** [comment] 2019-01-29 09:42
I remember seeing this. Cannot reproduce it on Ubuntu though so it is probably a Mac issue.
If you can live with it I would classify this as low priority since it is probably a lot of work and only a (minor?) inconvenience.

**Comment by aplested** [comment] 2022-03-21 08:50
I'm gonna close this issue, I can't reproduce it

**Closed by aplested** 2022-03-21 08:50 UTC
